name: development

services:
  database:
    image: mysql:8.2.0
    environment:
      MYSQL_ROOT_PASSWORD: secret
    ports:
      - 3306:3306
    volumes:
      - database:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 5s
      timeout: 10s
      retries: 10
      start_period: 10s
  redis:
    image: redis:7.2.3
    command: bash -c "redis-server --appendonly yes"
    ports:
      - 6379:6379
    volumes:
      - redis:/data
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 10s
      retries: 10
      start_period: 10s

  iamservice:
    build: IAMService/.
    ports:
      - 8000:8000
    environment:
      PORT: 8000
      DB_NAME: iamservice
      DB_HOST: database
      DB_PORT: 3306
      DB_USERNAME: root
      DB_PASSWORD: secret
      JWT_SECRET: abcdefgh
      JWT_REFRESH_SECRET: ijklmnop
      JWT_EXPIRES: 30m
      JWT_REFRESH_EXPIRES: 24h
    depends_on:
      database:
        condition: service_healthy
  financialservice:
    build: FinancialService/.
    ports:
      - 8001:8000
    environment:
      PORT: 8000
      DB_NAME: financialservice
      DB_HOST: database
      DB_PORT: 3306
      DB_USERNAME: root
      DB_PASSWORD: secret
    depends_on:
      database:
        condition: service_healthy


volumes:
  database:
    driver: local
  redis:
    driver: local