name: financialservice

services:
  redis:
    image: redis:7.2.3
    command: bash -c "redis-server --appendonly yes"
    ports:
      - 6379:6379
    volumes:
      - redis:/data
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      timeout: 20s
      retries: 10

volumes:
  redis:
    driver: local