name: iamservice

services:
  app:
    build: .
    ports:
      - 8000:8000
    environment:
      PORT: 8000
      DB_NAME: iamservice
      DB_HOST: database
      DB_PORT: 3306
      DB_USERNAME: root
      DB_PASSWORD: secret
      JWT_SECRET: abcdefgh
      JWT_REFRESH_SECRET: ijklmnop
      JWT_EXPIRES: 30m
      JWT_REFRESH_EXPIRES: 24h
    depends_on:
      database:
        condition: service_healthy

  database:
    image: mysql:8.2.0
    environment:
      MYSQL_ROOT_PASSWORD: secret
      MYSQL_DATABASE: iamservice
    ports:
      - 3306:3306
    volumes:
      - database:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost"]
      timeout: 20s
      retries: 10

volumes:
  database:
    driver: local